remote_theme: AndersDJohnson/andersdjohnson-jekyll-theme

plugins:
  - jemoji

andersdjohnson:
  # Use Google Analytics ID
  google_analytics: "G-GKW4WE5K60"
  # Show badges for npm
  npm_name: firedux
  # Show a badge for Travis CI
  travis: true
